'use client';

import { useEffect, useState } from 'react';
import { ambilApi, GalatApi } from '@/lib/api-client';
import { useSession, csrfHeaders } from '@/lib/sesi';
import { Button, Card, ConfirmAction, Field, PageTitle, SelectField, StateMessage, TextAreaField } from '@/components/ui';

type Template={id:string;slug:string;nama:string;aktif:boolean|number;currentVersionId:string|null;nomorVersi:number|null;tingkatAkses:'PUBLIK'|'INTERNAL';status:string|null};
export function AdminTemplates(){
 const {csrfToken}=useSession();const [rows,setRows]=useState<Template[]>([]);const [error,setError]=useState('');const [refresh,setRefresh]=useState(0);const [selected,setSelected]=useState<Template>();const [name,setName]=useState('');const [slug,setSlug]=useState('');const [description,setDescription]=useState('');const [access,setAccess]=useState<'PUBLIK'|'INTERNAL'>('PUBLIK');const [file,setFile]=useState<File>();
 useEffect(()=>{void ambilApi<Template[]>('/admin/letter-templates').then(setRows).catch(e=>setError(e instanceof GalatApi?e.message:'Daftar format tidak dapat dimuat.'));},[refresh]);
 function reset(){setSelected(undefined);setName('');setSlug('');setDescription('');setAccess('PUBLIK');setFile(undefined);}
 async function upload(){if(!file)throw new Error('Pilih berkas DOCX.');const data=new FormData();data.set('file',file);data.set('tingkatAkses',access);if(!selected){data.set('nama',name);data.set('slug',slug);data.set('deskripsi',description);}await ambilApi(selected?`/admin/letter-templates/${selected.id}/versions`:'/admin/letter-templates',{method:'POST',headers:csrfHeaders(csrfToken),muatan:data});reset();setRefresh(x=>x+1);}
 async function archive(row:Template){await ambilApi(`/admin/letter-templates/${row.id}/archive`,{method:'POST',headers:csrfHeaders(csrfToken),muatan:{}});setRefresh(x=>x+1);}
 return <div className="mx-auto max-w-6xl"><PageTitle title="Format Persuratan" description="Kelola template DOCX. Upload versi baru langsung menjadikannya ACTIVE; versi aktif sebelumnya disimpan sebagai arsip."/>{error&&<StateMessage title="Template belum dapat dimuat" kind="error">{error}</StateMessage>}
 <Card className="mb-5"><h2 className="font-bold">{selected?`Versi baru: ${selected.nama}`:'Tambah format persuratan'}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{!selected&&<><Field label="Nama" id="template-name" value={name} onChange={e=>setName(e.target.value)}/><Field label="Slug" id="template-slug" value={slug} onChange={e=>setSlug(e.target.value)}/><TextAreaField className="sm:col-span-2" label="Deskripsi (opsional)" id="template-desc" value={description} onChange={e=>setDescription(e.target.value)}/></>}<SelectField label="Akses" id="template-access" value={access} onChange={e=>setAccess(e.target.value as typeof access)}><option value="PUBLIK">Publik</option><option value="INTERNAL">Internal</option></SelectField><Field className="sm:col-span-2" label="Berkas DOCX" id="template-file" type="file" accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={e=>setFile(e.target.files?.[0])}/></div><div className="mt-4 flex gap-2"><ConfirmAction label={selected?'Unggah versi':'Buat template'} title={selected?'Unggah dan aktifkan versi baru?':'Buat template?'} description="Server memvalidasi MIME dan berkas. Upload versi baru mengarsipkan versi aktif sebelumnya." disabled={!file||(!selected&&(!name.trim()||!slug.trim()))} onConfirm={upload}/>{selected&&<Button tone="secondary" onClick={reset}>Batal</Button>}</div></Card>
 <div className="grid gap-3">{rows.map(row=><Card key={row.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-bold">{row.nama}</h2><p className="mt-1 text-sm text-slate-600">/{row.slug} · versi {row.nomorVersi??'—'} · {row.tingkatAkses} · {row.aktif?'Aktif':'Arsip'}</p></div><div className="flex gap-2"><Button tone="secondary" disabled={!row.aktif} onClick={()=>{setSelected(row);setAccess(row.tingkatAkses);}}>Versi baru</Button>{row.aktif&&<ConfirmAction label="Arsipkan" tone="danger" title="Arsipkan template?" description="Template tidak lagi tampil di daftar publik; riwayat versinya tetap disimpan." onConfirm={()=>archive(row)}/>}</div></div></Card>)}</div>
 </div>;
}
