'use client';

import { useEffect, useState } from 'react';
import { ambilApi, GalatApi } from '@/lib/api-client';
import { useSession, csrfHeaders } from '@/lib/sesi';
import { Button, Card, ConfirmAction, Field, PageTitle, SelectField, StateMessage, TextAreaField } from '@/components/ui';

type Unit = { id: string; nama: string; kode: string };
type PendingUser = { id: string; nama: string; email: string; unitManual: string|null; unitKerjaId: string|null; status: 'MENUNGGU_VERIFIKASI' };
export function AdminUsers() {
  const { csrfToken } = useSession(); const [rows, setRows] = useState<PendingUser[]>([]); const [units, setUnits] = useState<Unit[]>([]); const [selected, setSelected] = useState<PendingUser>(); const [unitId, setUnitId] = useState(''); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [notice,setNotice]=useState(''); const [refresh, setRefresh] = useState(0);
  useEffect(() => { void Promise.all([ambilApi<PendingUser[]>('/admin/users', { kueri: { halaman: 1, perHalaman: 100 } }), ambilApi<Unit[]>('/public/units')]).then(([users, unitRows]) => { setRows(users); setUnits(unitRows); }).catch((e) => setError(e instanceof GalatApi ? e.message : 'Antrean tidak dapat dimuat.')); }, [refresh]);
  async function decide(path: string, body: unknown) { await ambilApi(path, { method: 'POST', headers: csrfHeaders(csrfToken), muatan: body }); setNotice(path.endsWith('/approve')?'Akun berhasil disetujui.':'Pendaftaran berhasil ditolak.'); setSelected(undefined); setReason(''); setRefresh((x) => x+1); }
  return <div className="mx-auto max-w-6xl"><PageTitle title="Verifikasi pengguna" description="Antrean yang tersedia memuat pendaftaran DOSEN/STAF yang masih menunggu. API saat ini belum menyediakan daftar pencarian pengguna aktif." />
    {notice&&<p role="status" className="mb-4 rounded-lg border border-green-300 bg-green-50 p-3 text-sm text-green-900">{notice}</p>}{error && <StateMessage title="Antrean belum dapat dimuat" kind="error">{error}</StateMessage>}
    <Card className="mt-5"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="py-3">Nama</th><th>Email</th><th>Unit yang didaftarkan</th><th>Status</th><th></th></tr></thead><tbody className="divide-y">{rows.map((row) => <tr key={row.id}><td className="py-3 font-medium">{row.nama}</td><td>{row.email}</td><td>{row.unitManual ?? units.find((u) => u.id === row.unitKerjaId)?.nama ?? '—'}</td><td>{row.status}</td><td><Button tone="secondary" onClick={() => { setSelected(row); setUnitId(row.unitKerjaId ?? ''); }}>Tinjau</Button></td></tr>)}</tbody></table>{rows.length === 0 && <p className="py-6 text-sm text-slate-600">Tidak ada akun menunggu verifikasi.</p>}</div></Card>
    {selected && <div className="fixed inset-0 z-40 grid place-items-center overflow-y-auto bg-slate-950/50 p-4"><Card className="w-full max-w-xl"><h2 className="text-xl font-bold">Tinjau pendaftaran</h2><dl className="my-4 grid gap-2 text-sm"><div>{selected.nama} · {selected.email}</div><div>Unit manual: {selected.unitManual ?? '—'}</div></dl><div className="grid gap-4"><SelectField label="Unit master untuk persetujuan" id="approve-unit" value={unitId} onChange={(e) => setUnitId(e.target.value)}><option value="">Pilih unit</option>{units.map((u) => <option key={u.id} value={u.id}>{u.nama}</option>)}</SelectField><TextAreaField label="Alasan penolakan (wajib untuk menolak)" id="reject-reason" value={reason} onChange={(e) => setReason(e.target.value)} maxLength={1000} /><div className="flex flex-wrap justify-end gap-3"><Button tone="secondary" onClick={() => setSelected(undefined)}>Tutup</Button><ConfirmAction label="Tolak" tone="danger" title="Tolak pendaftaran ini?" description="Alasan penolakan akan dicatat pada audit." disabled={!reason.trim()} onConfirm={() => decide(`/admin/users/${selected.id}/reject`, { alasan: reason })} /><ConfirmAction label="Setujui" title="Setujui akun DOSEN/STAF?" description="Akun menjadi AKTIF dan baru eligible untuk mengakses Internal; backend tetap memeriksa izin pada setiap permintaan." disabled={!unitId} onConfirm={() => decide(`/admin/users/${selected.id}/approve`, { unitKerjaId: unitId })} /></div></div></Card></div>}
  </div>;
}
