'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ambilApi, ambilApiBerdaftar, GalatApi } from '@/lib/api-client';
import { useSession, csrfHeaders } from '@/lib/sesi';
import { Button, Card, ConfirmAction, Field, PageTitle, SelectField, StateMessage } from '@/components/ui';

type Master = { id: string; nama: string; aktif?: boolean };
type AdminDocumentRow = { id:string; versionId:string; judul:string; nomor:string|null; tahun:number|null; tipe:string; tingkatAkses:string; statusWorkflow:string; statusHukum:string };
export function AdminDocuments() {
  return <DaftarDokumenAdmin />;
}

export function DaftarDokumenAdmin({ verificationOnly=false }:{verificationOnly?:boolean}) {
  const [rows,setRows]=useState<readonly AdminDocumentRow[]>([]);const [query,setQuery]=useState('');const [status,setStatus]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [refresh,setRefresh]=useState(0);const [page,setPage]=useState(1);const [totalPages,setTotalPages]=useState(0);
  useEffect(()=>{let current=true;void ambilApiBerdaftar<AdminDocumentRow>(verificationOnly?'/admin/documents/verification-queue':'/admin/documents',{kueri:{halaman:page,perHalaman:30,q:query||undefined,statusWorkflow:verificationOnly?undefined:status||undefined}}).then(r=>{if(current){setRows(r.data);setTotalPages(r.meta.totalHalaman);setError('');}}).catch((e:unknown)=>{if(current)setError(e instanceof GalatApi?e.message:'Daftar dokumen tidak dapat dimuat.');}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[query,status,verificationOnly,refresh,page]);
  return <div className="mx-auto max-w-6xl"><PageTitle title={verificationOnly?'Antrean verifikasi dokumen':'Dokumen Hukum'} description={verificationOnly?'Versi berstatus DIAJUKAN yang dapat ditinjau sesuai izin Anda.':'Daftar semua versi dokumen dengan filter status workflow.'} action={!verificationOnly&&<Link href="/admin/dokumen/baru" className="inline-flex min-h-11 items-center rounded-md bg-blue-900 px-4 font-semibold text-white">Buat dokumen</Link>} />
    <Card><form className="mb-4 grid gap-3 sm:grid-cols-[1fr_220px_auto]" onSubmit={e=>{e.preventDefault();setLoading(true);setRefresh(x=>x+1);}}><Field className="min-w-0" label="Cari judul, nomor, atau slug" id="admin-doc-q" value={query} onChange={e=>{setLoading(true);setQuery(e.target.value);setPage(1);}} placeholder="Kata kunci"/>{!verificationOnly&&<SelectField label="Status workflow" id="admin-doc-status" value={status} onChange={e=>{setLoading(true);setStatus(e.target.value);setPage(1);}}><option value="">Semua status</option>{['DRAF','DIAJUKAN','REVISI','DISETUJUI','TERBIT','DITARIK'].map(v=><option key={v}>{v}</option>)}</SelectField>}<div className="self-end"><Button type="submit">Muat ulang</Button></div></form>{error&&<StateMessage title="Daftar gagal dimuat" kind="error">{error}</StateMessage>}{loading&&<StateMessage title="Memuat dokumen…"/>}{!loading&&!error&&rows.length===0&&<StateMessage title="Tidak ada dokumen">Tidak ada baris yang cocok dengan filter.</StateMessage>}
      {!loading&&!error&&rows.length>0&&<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b text-slate-600"><th className="py-3">Dokumen</th><th>Jenis / nomor</th><th>Akses</th><th>Status workflow</th><th>Status hukum</th></tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.versionId}><td className="py-3"><Link className="font-semibold text-blue-900 underline" href={`/admin/dokumen/${r.id}?versionId=${r.versionId}`}>{r.judul}</Link><div className="text-xs text-slate-500">Versi ID {r.versionId}</div></td><td>{r.tipe} · {r.nomor??'—'} · {r.tahun??'—'}</td><td>{r.tingkatAkses.toUpperCase()}</td><td>{r.statusWorkflow}</td><td>{r.statusHukum}</td></tr>)}</tbody></table></div>}
      {totalPages>1&&<div className="mt-4 flex items-center justify-between"><Button tone="secondary" disabled={page<=1||loading} onClick={()=>{setLoading(true);setPage(p=>p-1);}}>Sebelumnya</Button><span className="text-sm">Halaman {page} dari {totalPages}</span><Button tone="secondary" disabled={page>=totalPages||loading} onClick={()=>{setLoading(true);setPage(p=>p+1);}}>Berikutnya</Button></div>}
    </Card>
  </div>;
}

export function AdminVerificationQueue(){return <DaftarDokumenAdmin verificationOnly/>;}

export function AdminDocumentCreate() {
  const { csrfToken } = useSession(); const [types,setTypes]=useState<Master[]>([]); const [categories,setCategories]=useState<Master[]>([]); const [units,setUnits]=useState<Master[]>([]); const [code,setCode]=useState(''); const [slug,setSlug]=useState(''); const [type,setType]=useState(''); const [title,setTitle]=useState(''); const [access,setAccess]=useState<'publik'|'internal'|'rahasia'>('publik'); const [number,setNumber]=useState(''); const [year,setYear]=useState(''); const [pic,setPic]=useState(''); const [date,setDate]=useState(''); const [unit,setUnit]=useState(''); const [category,setCategory]=useState(''); const [error,setError]=useState(''); const [created,setCreated]=useState<{id:string;versionId:string}>();
  useEffect(()=>{void Promise.all([ambilApi<Master[]>('/admin/master/jenis_dokumen'),ambilApi<Master[]>('/admin/master/kategori'),ambilApi<Master[]>('/public/units')]).then(([a,b,c])=>{setTypes(a);setCategories(b);setUnits(c);}).catch(e=>setError(e instanceof GalatApi?e.message:'Data pilihan tidak dapat dimuat.'));},[]);
  async function create(){const result=await ambilApi<{id:string;versionId:string}>('/admin/documents',{method:'POST',headers:csrfHeaders(csrfToken),muatan:{kodeDokumen:code,slug,jenisDokumenId:type,versi:{judul:title,nomor:number||undefined,tahun:year?Number(year):undefined,pic:pic||undefined,tanggalPenetapan:date||undefined,tingkatAkses:access,unitKerjaId:unit||undefined,kategoriId:category?[category]:[]}}});setCreated(result);}
  if(created)return <div className="mx-auto max-w-3xl"><StateMessage title="Draf dokumen dibuat">Versi draf #{created.versionId} berhasil dibuat. Unggah metadata file UTAMA pada halaman detail sebelum mengajukan untuk verifikasi.</StateMessage><Link className="mt-5 inline-block font-semibold underline" href={`/admin/dokumen/${created.id}`}>Buka detail draf</Link></div>;
  return <div className="mx-auto max-w-4xl"><PageTitle title="Buat dokumen hukum" description="Informasi dibuat sebagai draf; metadata publikasi dan file utama dapat dilengkapi sebelum workflow." />{error&&<StateMessage title="Data form belum tersedia" kind="error">{error}</StateMessage>}<Card><div className="grid gap-4 sm:grid-cols-2"><Field label="Kode dokumen" id="doc-code" required value={code} onChange={e=>setCode(e.target.value)} maxLength={64}/><Field label="Slug URL" id="doc-slug" required value={slug} onChange={e=>setSlug(e.target.value)} maxLength={160}/><SelectField label="Jenis dokumen" id="doc-type" required value={type} onChange={e=>setType(e.target.value)}><option value="">Pilih jenis</option>{types.filter(x=>x.aktif!==false).map(x=><option key={x.id} value={x.id}>{x.nama}</option>)}</SelectField><SelectField label="Tingkat akses" id="doc-access" value={access} onChange={e=>setAccess(e.target.value as typeof access)}><option value="publik">Publik</option><option value="internal">Internal</option><option value="rahasia">Rahasia</option></SelectField><Field className="sm:col-span-2" label="Judul" id="doc-title" required value={title} onChange={e=>setTitle(e.target.value)} maxLength={500}/><Field label="Nomor (opsional saat draf)" id="doc-number" value={number} onChange={e=>setNumber(e.target.value)}/><Field label="Tahun" id="doc-year" inputMode="numeric" value={year} onChange={e=>setYear(e.target.value)}/><Field label="PIC" id="doc-pic" value={pic} onChange={e=>setPic(e.target.value)}/><Field label="Tanggal penetapan" id="doc-date" type="date" value={date} onChange={e=>setDate(e.target.value)}/><SelectField label="Unit kerja" id="doc-unit" value={unit} onChange={e=>setUnit(e.target.value)}><option value="">Tanpa unit</option>{units.map(x=><option key={x.id} value={x.id}>{x.nama}</option>)}</SelectField><SelectField label="Kategori" id="doc-category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Tanpa kategori</option>{categories.map(x=><option key={x.id} value={x.id}>{x.nama}</option>)}</SelectField></div><div className="mt-6"><ConfirmAction label="Buat draf" title="Buat draf dokumen?" description="Draf ini belum dapat diakses sebagai dokumen terbit. Pastikan metadata dasarnya benar." disabled={!code.trim()||!slug.trim()||!type||!title.trim()} onConfirm={create}/></div></Card></div>;
}
